name = "BulkLMM"
uuid = "654ff64a-de8a-4d95-ac2a-94859e9c1c25"
authors = ["Saunak Sen <sen@uthsc.edu> and contributors"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[compat]
julia = "1.7"
